version: '3.5'

services:
  db-development:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres      
    volumes:
      - db-development:/data/postgres
      - ./db/base/01-create_tables.sql:/docker-entrypoint-initdb.d/01-create_tables.sql
      - ./db/base/02-load-data.sql:/docker-entrypoint-initdb.d/02-load-data.sql
    ports:
      - ${DB_PORT}:5432
    networks:
      - db-development
    restart: unless-stopped
  db-test:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_TESTNAME}
      POSTGRES_USER: ${DB_TESTUSERNAME}
      POSTGRES_PASSWORD: ${DB_TESTPASSWORD}
      PGDATA: /data/postgres      
    volumes:
      - db-test:/data/postgres
      - ./db/base/01-create_tables.sql:/docker-entrypoint-initdb.d/01-create_tables.sql
      - ./db/test/02-load-data-test.sql:/docker-entrypoint-initdb.d/02-load-data-test.sql
    ports:
      - ${DB_TESTPORT}:5432
    networks:
      - db-test
    restart: unless-stopped

networks:
  db-development:
    driver: bridge
  db-test:
    driver: bridge

volumes:
    db-development:
    db-test: